development:
  adapter: mysql2
  database: gamerankr_dev
  username: gamerankr
  password: pass

test:
  adapter: mysql2
  database: gamerankr_test
  username: gamerankr
  password: pass

# production:
#   adapter: mysql2
#   database: gamerankr_prod
#   username: gamerankr
#   password: pass
